name = "BigGold26v2"
author = "ted2_0"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "70e2cf4320209b631b4af0d6f7c3bec752f29a24af0ae1bcb5ba25d392d41c91"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
