name = "BigGold26v2"
author = "ted2_0"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6e8f43e2ecb7a3dbbf42bf013049868278c5b9c77070b520da4395edc362ecc0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
